<div class="box">
    <div class="box-title">
        Loto đầu đuôi
    </div>
    <div class="box-content row">
        <div class="col-md-6">
            <table class="table tb-result table-bordered">
                <tr>
                    <td>@print($startLoto[0])</td>
                    <td>@print($startLoto[1])</td>
                </tr>
                <tr>
                    <td>@print($startLoto[2])</td>
                    <td>@print($startLoto[3])</td>
                </tr>
                <tr>
                    <td>@print($startLoto[4])</td>
                    <td>@print($startLoto[5])</td>
                </tr>
                <tr>
                    <td>@print($startLoto[6])</td>
                    <td>@print($startLoto[7])</td>
                </tr>
                <tr>
                    <td>@print($startLoto[8])</td>
                    <td>@print($startLoto[9])</td>
                </tr>
                <tr>
                    <td>@print($startLoto[10])</td>
                    <td>@print($startLoto[11])</td>
                </tr>
                <tr>
                    <td>@print($startLoto[12])</td>
                    <td>@print($startLoto[13])</td>
                </tr>
                <tr>
                    <td>@print($startLoto[14])</td>
                    <td>@print($startLoto[15])</td>
                </tr>
                <tr>
                    <td>@print($startLoto[16])</td>
                    <td>@print($startLoto[17])</td>
                </tr>
                <tr>
                    <td>@print($startLoto[18])</td>
                    <td>@print($startLoto[19])</td>
                </tr>
                <tr>
                    <td>@print($startLoto[20])</td>
                    <td>@print($startLoto[21])</td>
                </tr>
            </table>
        </div>
        <div class="col-md-6">
            <table class="table tb-result table-bordered">
                <tr>
                    <td>@print($endLoto[0])</td>
                    <td>@print($endLoto[1])</td>
                </tr>
                <tr>
                    <td>@print($endLoto[2])</td>
                    <td>@print($endLoto[3])</td>
                </tr>
                <tr>
                    <td>@print($endLoto[4])</td>
                    <td>@print($endLoto[5])</td>
                </tr>
                <tr>
                    <td>@print($endLoto[6])</td>
                    <td>@print($endLoto[7])</td>
                </tr>
                <tr>
                    <td>@print($endLoto[8])</td>
                    <td>@print($endLoto[9])</td>
                </tr>
                <tr>
                    <td>@print($endLoto[10])</td>
                    <td>@print($endLoto[11])</td>
                </tr>
                <tr>
                    <td>@print($endLoto[12])</td>
                    <td>@print($endLoto[13])</td>
                </tr>
                <tr>
                    <td>@print($endLoto[14])</td>
                    <td>@print($endLoto[15])</td>
                </tr>
                <tr>
                    <td>@print($endLoto[16])</td>
                    <td>@print($endLoto[17])</td>
                </tr>
                <tr>
                    <td>@print($endLoto[18])</td>
                    <td>@print($endLoto[19])</td>
                </tr>
                <tr>
                    <td>@print($endLoto[20])</td>
                    <td>@print($endLoto[21])</td>
                </tr>
            </table>
        </div>
    </div>
</div>